### ISSUE TITLE
Question about Table 1: Initial Retrieval Results

### ISSUE THREAD

**Issue by kiucho** [lezhang7/Retrieval_MuGI#1]
First of all, Thanks for sharing your great research.

Comparing with Query2Doc, Stage 1 of MuGI seems very similar to Query2Doc.
As described in the section 3 of the paper, the difference between Query2Doc and MuGI's stage1 is as follow:
Query2Doc utilizes Few-shot examples to generate pseudo references, but stage1 of MuGI utilizes novel Zero-shot Prompting.

Then, I have questions about Table1: Initial Retrieval Results.
1. Is the result of Query2Doc in table 1 utlizes few-shot or zero-shot?
2. If both Query2Doc and MuGI utilized same prompting, what could be the reason stage 1 of MuGI is better than Query2Doc?

Thanks.

**Comment by lezhang7** [comment]
Hi,

Thanks for the interest in our work.

The main differences lie in that we use multiple generated text and
integrate query and documents with a different query repetition strategy.

Query2doc generated only one passages, while we find more passages leads to
higher result, moreover, to balance the weight between query and documents,
we adopt a dynamic repetition instead of constant repetition (ie. 5) as in
query2doc. Hope this could answer your question, let me know if you have
further questions.

Best
Le



KIUCHO ***@***.***>于2024年1月22日 周一上午12:28写道：

**Comment by kiucho** [comment]
Thanks for your kind reply.

I understood 2 reasons why MuGI's stage 1 is better than Query2Doc.
1. Multiple pseudo passage generation to ensure contextually relevant and diverse content.
2. Dynamic approach in repeating queries for sparse retriever.

Thanks again!

**Comment by kiucho** [comment]
I reopened this issue for another question.

As I understand it, query and pseudo-passages (generated by LLM) used for sparse retrieval (Stage 1: initial retrieval) are re-used for dense retrieval (Stage 2: re-rank).

But in the Section 4 of the paper, it states:
"In this study, we use passages from ChatGPT3.5-turbo for dense query and passages from ChatGPT4-turbo for sparase retrieval, targeting improved performance and cost efficiency."

Since stage 1 already used ChatGPT4-turbo to generate the pseudo-passages, I was wondering why stage 2 utilized the new pseudo-passages from ChatGPT3.5-turbo instead of re-using the pseudo-passages from ChatGPT4-turbo in stage 1.

**Comment by lezhang7** [comment]
Hey kiuchou,

Yes you are right, we experically find that for sparse retrieval, gpt4 generated docs perform much better than gpt35 generated, while in dense retrieval the results reverse. The explanation is: for dense retrieval gpt4 generated docs are longer and contain more information, possibly due to instruction tuning result of gpt4. These additional information could help BM25 identify key vocabulary therefore enhance retrieval results. However, for dense retrieval, which are usually smaller models, the increased information from gpt4 generated docs could also inject more noise, and confuse the dense retriever and they behave better on gpt35 generated docs.

**Comment by kiucho** [comment]
Thanks for your kind explanation!

In the Table 1 of the paper, which reports "Initial Retrieval Results", I have a question about scores of LLM API (DL19 and DL20)

LameR(https://arxiv.org/pdf/2304.14233.pdf) reported they got 69.1 and 64.8 in DL19 and DL20 repectively with GPT-3.5-turbo. But in the Table1 of MuGI, it says LameR got 67.1 and 62.7. Can I know what has been changed in the setting of LameR?

**Comment by lezhang7** [comment]
you are right, thanks for mentioning this, our results of LameR are extracted from https://arxiv.org/pdf/2304.14233v1.pdf, which is their first version draft, i will update this in our next version of the paper.

**Comment by kiucho** [comment]
Oh,, looks like my mistake was due to not checking the early version of LameR.
Thank you so much for your kind reply!!!
